var Libs_Item = {
  0: {ItemTypeId: '1', Name: 'nothing', Size: '1', IsBlocking: '1', IsMoveable: '0', IsPickupable: '0', IsAlwaysUnder: '1', IsAlwaysTop: '0', LightLevel: '0', LightColor: '#000000'},
  1000: {ItemTypeId: '1', Name: 'water', Size: '1', IsBlocking: '1', IsMoveable: '0', IsPickupable: '0', IsAlwaysUnder: '1', IsAlwaysTop: '0', LightLevel: '0', LightColor: '#000000'},
  1001: {ItemTypeId: '1', Name: 'sand', Size: '1', IsBlocking: '0', IsMoveable: '0', IsPickupable: '0', IsAlwaysUnder: '1', IsAlwaysTop: '0', LightLevel: '0', LightColor: '#000000'},
  1002: {ItemTypeId: '1', Name: 'stone tile', Size: '1', IsBlocking: '0', IsMoveable: '0', IsPickupable: '0', IsAlwaysUnder: '1', IsAlwaysTop: '0', LightLevel: '0', LightColor: '#000000'},
  1003: {ItemTypeId: '1', Name: 'grass', Size: '1', IsBlocking: '0', IsMoveable: '0', IsPickupable: '0', IsAlwaysUnder: '1', IsAlwaysTop: '0', LightLevel: '0', LightColor: '#000000'},
  1004: {ItemTypeId: '1', Name: 'stone floor', Size: '1', IsBlocking: '0', IsMoveable: '0', IsPickupable: '0', IsAlwaysUnder: '1', IsAlwaysTop: '0', LightLevel: '0', LightColor: '#000000'},
  1005: {ItemTypeId: '1', Name: 'white tile', Size: '1', IsBlocking: '0', IsMoveable: '0', IsPickupable: '0', IsAlwaysUnder: '1', IsAlwaysTop: '0', LightLevel: '0', LightColor: '#000000'},
  1006: {ItemTypeId: '1', Name: 'black tile', Size: '1', IsBlocking: '0', IsMoveable: '0', IsPickupable: '0', IsAlwaysUnder: '1', IsAlwaysTop: '0', LightLevel: '0', LightColor: '#000000'},
  1007: {ItemTypeId: '1', Name: 'dirt', Size: '1', IsBlocking: '0', IsMoveable: '0', IsPickupable: '0', IsAlwaysUnder: '1', IsAlwaysTop: '0', LightLevel: '0', LightColor: '#000000'},
  1008: {ItemTypeId: '1', Name: 'wooden floor', Size: '1', IsBlocking: '0', IsMoveable: '0', IsPickupable: '0', IsAlwaysUnder: '1', IsAlwaysTop: '0', LightLevel: '0', LightColor: '#000000'},
  1009: {ItemTypeId: '1', Name: 'void', Size: '1', IsBlocking: '1', IsMoveable: '0', IsPickupable: '0', IsAlwaysUnder: '1', IsAlwaysTop: '0', LightLevel: '0', LightColor: '#000000'},
  1010: {ItemTypeId: '1', Name: 'stone floor', Size: '1', IsBlocking: '0', IsMoveable: '0', IsPickupable: '0', IsAlwaysUnder: '1', IsAlwaysTop: '0', LightLevel: '0', LightColor: '#000000'},
  1011: {ItemTypeId: '1', Name: 'stone floor', Size: '1', IsBlocking: '0', IsMoveable: '0', IsPickupable: '0', IsAlwaysUnder: '1', IsAlwaysTop: '0', LightLevel: '0', LightColor: '#000000'},
  2000: {ItemTypeId: '2', Name: 'water shore', Size: '1', IsBlocking: '1', IsMoveable: '0', IsPickupable: '0', IsAlwaysUnder: '1', IsAlwaysTop: '0', LightLevel: '0', LightColor: '#000000'},
  2001: {ItemTypeId: '2', Name: 'water shore', Size: '1', IsBlocking: '1', IsMoveable: '0', IsPickupable: '0', IsAlwaysUnder: '1', IsAlwaysTop: '0', LightLevel: '0', LightColor: '#000000'},
  2002: {ItemTypeId: '2', Name: 'water shore', Size: '1', IsBlocking: '1', IsMoveable: '0', IsPickupable: '0', IsAlwaysUnder: '1', IsAlwaysTop: '0', LightLevel: '0', LightColor: '#000000'},
  2003: {ItemTypeId: '2', Name: 'water shore', Size: '1', IsBlocking: '1', IsMoveable: '0', IsPickupable: '0', IsAlwaysUnder: '1', IsAlwaysTop: '0', LightLevel: '0', LightColor: '#000000'},
  2004: {ItemTypeId: '2', Name: 'water shore', Size: '1', IsBlocking: '1', IsMoveable: '0', IsPickupable: '0', IsAlwaysUnder: '1', IsAlwaysTop: '0', LightLevel: '0', LightColor: '#000000'},
  2005: {ItemTypeId: '2', Name: 'water shore', Size: '1', IsBlocking: '1', IsMoveable: '0', IsPickupable: '0', IsAlwaysUnder: '1', IsAlwaysTop: '0', LightLevel: '0', LightColor: '#000000'},
  2006: {ItemTypeId: '2', Name: 'water shore', Size: '1', IsBlocking: '1', IsMoveable: '0', IsPickupable: '0', IsAlwaysUnder: '1', IsAlwaysTop: '0', LightLevel: '0', LightColor: '#000000'},
  2007: {ItemTypeId: '2', Name: 'water shore', Size: '1', IsBlocking: '1', IsMoveable: '0', IsPickupable: '0', IsAlwaysUnder: '1', IsAlwaysTop: '0', LightLevel: '0', LightColor: '#000000'},
  2008: {ItemTypeId: '2', Name: 'water shore', Size: '1', IsBlocking: '1', IsMoveable: '0', IsPickupable: '0', IsAlwaysUnder: '1', IsAlwaysTop: '0', LightLevel: '0', LightColor: '#000000'},
  2009: {ItemTypeId: '2', Name: 'water shore', Size: '1', IsBlocking: '1', IsMoveable: '0', IsPickupable: '0', IsAlwaysUnder: '1', IsAlwaysTop: '0', LightLevel: '0', LightColor: '#000000'},
  2010: {ItemTypeId: '2', Name: 'water shore', Size: '1', IsBlocking: '1', IsMoveable: '0', IsPickupable: '0', IsAlwaysUnder: '1', IsAlwaysTop: '0', LightLevel: '0', LightColor: '#000000'},
  2011: {ItemTypeId: '2', Name: 'water shore', Size: '1', IsBlocking: '1', IsMoveable: '0', IsPickupable: '0', IsAlwaysUnder: '1', IsAlwaysTop: '0', LightLevel: '0', LightColor: '#000000'},
  2012: {ItemTypeId: '2', Name: 'grass shore', Size: '1', IsBlocking: '0', IsMoveable: '0', IsPickupable: '0', IsAlwaysUnder: '1', IsAlwaysTop: '0', LightLevel: '0', LightColor: '#000000'},
  2013: {ItemTypeId: '2', Name: 'grass shore', Size: '1', IsBlocking: '0', IsMoveable: '0', IsPickupable: '0', IsAlwaysUnder: '1', IsAlwaysTop: '0', LightLevel: '0', LightColor: '#000000'},
  2014: {ItemTypeId: '2', Name: 'grass shore', Size: '1', IsBlocking: '0', IsMoveable: '0', IsPickupable: '0', IsAlwaysUnder: '1', IsAlwaysTop: '0', LightLevel: '0', LightColor: '#000000'},
  2015: {ItemTypeId: '2', Name: 'grass shore', Size: '1', IsBlocking: '0', IsMoveable: '0', IsPickupable: '0', IsAlwaysUnder: '1', IsAlwaysTop: '0', LightLevel: '0', LightColor: '#000000'},
  2016: {ItemTypeId: '2', Name: 'grass shore', Size: '1', IsBlocking: '0', IsMoveable: '0', IsPickupable: '0', IsAlwaysUnder: '1', IsAlwaysTop: '0', LightLevel: '0', LightColor: '#000000'},
  2017: {ItemTypeId: '2', Name: 'grass shore', Size: '1', IsBlocking: '0', IsMoveable: '0', IsPickupable: '0', IsAlwaysUnder: '1', IsAlwaysTop: '0', LightLevel: '0', LightColor: '#000000'},
  2018: {ItemTypeId: '2', Name: 'grass shore', Size: '1', IsBlocking: '0', IsMoveable: '0', IsPickupable: '0', IsAlwaysUnder: '1', IsAlwaysTop: '0', LightLevel: '0', LightColor: '#000000'},
  2019: {ItemTypeId: '2', Name: 'grass shore', Size: '1', IsBlocking: '0', IsMoveable: '0', IsPickupable: '0', IsAlwaysUnder: '1', IsAlwaysTop: '0', LightLevel: '0', LightColor: '#000000'},
  2020: {ItemTypeId: '2', Name: 'grass shore', Size: '1', IsBlocking: '0', IsMoveable: '0', IsPickupable: '0', IsAlwaysUnder: '1', IsAlwaysTop: '0', LightLevel: '0', LightColor: '#000000'},
  2021: {ItemTypeId: '2', Name: 'grass shore', Size: '1', IsBlocking: '0', IsMoveable: '0', IsPickupable: '0', IsAlwaysUnder: '1', IsAlwaysTop: '0', LightLevel: '0', LightColor: '#000000'},
  2022: {ItemTypeId: '2', Name: 'grass shore', Size: '1', IsBlocking: '0', IsMoveable: '0', IsPickupable: '0', IsAlwaysUnder: '1', IsAlwaysTop: '0', LightLevel: '0', LightColor: '#000000'},
  2023: {ItemTypeId: '2', Name: 'grass shore', Size: '1', IsBlocking: '0', IsMoveable: '0', IsPickupable: '0', IsAlwaysUnder: '1', IsAlwaysTop: '0', LightLevel: '0', LightColor: '#000000'},
  2024: {ItemTypeId: '2', Name: 'dirt shore', Size: '1', IsBlocking: '0', IsMoveable: '0', IsPickupable: '0', IsAlwaysUnder: '1', IsAlwaysTop: '0', LightLevel: '0', LightColor: '#000000'},
  2025: {ItemTypeId: '2', Name: 'dirt shore', Size: '1', IsBlocking: '0', IsMoveable: '0', IsPickupable: '0', IsAlwaysUnder: '1', IsAlwaysTop: '0', LightLevel: '0', LightColor: '#000000'},
  2026: {ItemTypeId: '2', Name: 'dirt shore', Size: '1', IsBlocking: '0', IsMoveable: '0', IsPickupable: '0', IsAlwaysUnder: '1', IsAlwaysTop: '0', LightLevel: '0', LightColor: '#000000'},
  2027: {ItemTypeId: '2', Name: 'dirt shore', Size: '1', IsBlocking: '0', IsMoveable: '0', IsPickupable: '0', IsAlwaysUnder: '1', IsAlwaysTop: '0', LightLevel: '0', LightColor: '#000000'},
  2028: {ItemTypeId: '2', Name: 'dirt shore', Size: '1', IsBlocking: '0', IsMoveable: '0', IsPickupable: '0', IsAlwaysUnder: '1', IsAlwaysTop: '0', LightLevel: '0', LightColor: '#000000'},
  2029: {ItemTypeId: '2', Name: 'dirt shore', Size: '1', IsBlocking: '0', IsMoveable: '0', IsPickupable: '0', IsAlwaysUnder: '1', IsAlwaysTop: '0', LightLevel: '0', LightColor: '#000000'},
  2030: {ItemTypeId: '2', Name: 'dirt shore', Size: '1', IsBlocking: '0', IsMoveable: '0', IsPickupable: '0', IsAlwaysUnder: '1', IsAlwaysTop: '0', LightLevel: '0', LightColor: '#000000'},
  2031: {ItemTypeId: '2', Name: 'dirt shore', Size: '1', IsBlocking: '0', IsMoveable: '0', IsPickupable: '0', IsAlwaysUnder: '1', IsAlwaysTop: '0', LightLevel: '0', LightColor: '#000000'},
  2032: {ItemTypeId: '2', Name: 'dirt shore', Size: '1', IsBlocking: '0', IsMoveable: '0', IsPickupable: '0', IsAlwaysUnder: '1', IsAlwaysTop: '0', LightLevel: '0', LightColor: '#000000'},
  2033: {ItemTypeId: '2', Name: 'dirt shore', Size: '1', IsBlocking: '0', IsMoveable: '0', IsPickupable: '0', IsAlwaysUnder: '1', IsAlwaysTop: '0', LightLevel: '0', LightColor: '#000000'},
  2034: {ItemTypeId: '2', Name: 'dirt shore', Size: '1', IsBlocking: '0', IsMoveable: '0', IsPickupable: '0', IsAlwaysUnder: '1', IsAlwaysTop: '0', LightLevel: '0', LightColor: '#000000'},
  2035: {ItemTypeId: '2', Name: 'dirt shore', Size: '1', IsBlocking: '0', IsMoveable: '0', IsPickupable: '0', IsAlwaysUnder: '1', IsAlwaysTop: '0', LightLevel: '0', LightColor: '#000000'},
  3000: {ItemTypeId: '3', Name: 'framework wall', Size: '2', IsBlocking: '1', IsMoveable: '0', IsPickupable: '0', IsAlwaysUnder: '0', IsAlwaysTop: '0', LightLevel: '0', LightColor: '#000000'},
  3001: {ItemTypeId: '3', Name: 'framework wall', Size: '2', IsBlocking: '1', IsMoveable: '0', IsPickupable: '0', IsAlwaysUnder: '0', IsAlwaysTop: '0', LightLevel: '0', LightColor: '#000000'},
  3002: {ItemTypeId: '3', Name: 'framework wall', Size: '2', IsBlocking: '1', IsMoveable: '0', IsPickupable: '0', IsAlwaysUnder: '0', IsAlwaysTop: '0', LightLevel: '0', LightColor: '#000000'},
  3003: {ItemTypeId: '3', Name: 'framework wall', Size: '2', IsBlocking: '1', IsMoveable: '0', IsPickupable: '0', IsAlwaysUnder: '0', IsAlwaysTop: '0', LightLevel: '0', LightColor: '#000000'},
  3004: {ItemTypeId: '3', Name: 'stone wall', Size: '2', IsBlocking: '1', IsMoveable: '0', IsPickupable: '0', IsAlwaysUnder: '0', IsAlwaysTop: '0', LightLevel: '0', LightColor: '#000000'},
  3005: {ItemTypeId: '3', Name: 'stone wall', Size: '2', IsBlocking: '1', IsMoveable: '0', IsPickupable: '0', IsAlwaysUnder: '0', IsAlwaysTop: '0', LightLevel: '0', LightColor: '#000000'},
  3006: {ItemTypeId: '3', Name: 'stone wall', Size: '2', IsBlocking: '1', IsMoveable: '0', IsPickupable: '0', IsAlwaysUnder: '0', IsAlwaysTop: '0', LightLevel: '0', LightColor: '#000000'},
  3007: {ItemTypeId: '3', Name: 'stone wall', Size: '2', IsBlocking: '1', IsMoveable: '0', IsPickupable: '0', IsAlwaysUnder: '0', IsAlwaysTop: '0', LightLevel: '0', LightColor: '#000000'},
  3008: {ItemTypeId: '3', Name: 'low stone wall', Size: '2', IsBlocking: '1', IsMoveable: '0', IsPickupable: '0', IsAlwaysUnder: '0', IsAlwaysTop: '0', LightLevel: '0', LightColor: '#000000'},
  3009: {ItemTypeId: '3', Name: 'low stone wall', Size: '2', IsBlocking: '1', IsMoveable: '0', IsPickupable: '0', IsAlwaysUnder: '0', IsAlwaysTop: '0', LightLevel: '0', LightColor: '#000000'},
  3010: {ItemTypeId: '3', Name: 'low stone wall', Size: '2', IsBlocking: '1', IsMoveable: '0', IsPickupable: '0', IsAlwaysUnder: '0', IsAlwaysTop: '0', LightLevel: '0', LightColor: '#000000'},
  3011: {ItemTypeId: '3', Name: 'low stone wall', Size: '2', IsBlocking: '1', IsMoveable: '0', IsPickupable: '0', IsAlwaysUnder: '0', IsAlwaysTop: '0', LightLevel: '0', LightColor: '#000000'},
  3012: {ItemTypeId: '3', Name: 'stone wall', Size: '2', IsBlocking: '1', IsMoveable: '0', IsPickupable: '0', IsAlwaysUnder: '0', IsAlwaysTop: '0', LightLevel: '0', LightColor: '#000000'},
  3013: {ItemTypeId: '3', Name: 'stone wall', Size: '2', IsBlocking: '1', IsMoveable: '0', IsPickupable: '0', IsAlwaysUnder: '0', IsAlwaysTop: '0', LightLevel: '0', LightColor: '#000000'},
  3014: {ItemTypeId: '3', Name: 'stone wall', Size: '2', IsBlocking: '1', IsMoveable: '0', IsPickupable: '0', IsAlwaysUnder: '0', IsAlwaysTop: '0', LightLevel: '0', LightColor: '#000000'},
  3015: {ItemTypeId: '3', Name: 'stone wall', Size: '2', IsBlocking: '1', IsMoveable: '0', IsPickupable: '0', IsAlwaysUnder: '0', IsAlwaysTop: '0', LightLevel: '0', LightColor: '#000000'},
  3016: {ItemTypeId: '3', Name: 'low stone wall', Size: '2', IsBlocking: '1', IsMoveable: '0', IsPickupable: '0', IsAlwaysUnder: '0', IsAlwaysTop: '0', LightLevel: '0', LightColor: '#000000'},
  3017: {ItemTypeId: '3', Name: 'low stone wall', Size: '2', IsBlocking: '1', IsMoveable: '0', IsPickupable: '0', IsAlwaysUnder: '0', IsAlwaysTop: '0', LightLevel: '0', LightColor: '#000000'},
  3018: {ItemTypeId: '3', Name: 'low stone wall', Size: '2', IsBlocking: '1', IsMoveable: '0', IsPickupable: '0', IsAlwaysUnder: '0', IsAlwaysTop: '0', LightLevel: '0', LightColor: '#000000'},
  3019: {ItemTypeId: '3', Name: 'low stone wall', Size: '2', IsBlocking: '1', IsMoveable: '0', IsPickupable: '0', IsAlwaysUnder: '0', IsAlwaysTop: '0', LightLevel: '0', LightColor: '#000000'},
  3020: {ItemTypeId: '3', Name: 'mountain', Size: '2', IsBlocking: '1', IsMoveable: '0', IsPickupable: '0', IsAlwaysUnder: '0', IsAlwaysTop: '0', LightLevel: '0', LightColor: '#000000'},
  3021: {ItemTypeId: '3', Name: 'mountain', Size: '2', IsBlocking: '1', IsMoveable: '0', IsPickupable: '0', IsAlwaysUnder: '0', IsAlwaysTop: '0', LightLevel: '0', LightColor: '#000000'},
  3022: {ItemTypeId: '3', Name: 'mountain', Size: '2', IsBlocking: '1', IsMoveable: '0', IsPickupable: '0', IsAlwaysUnder: '0', IsAlwaysTop: '0', LightLevel: '0', LightColor: '#000000'},
  3023: {ItemTypeId: '3', Name: 'mountain', Size: '2', IsBlocking: '1', IsMoveable: '0', IsPickupable: '0', IsAlwaysUnder: '0', IsAlwaysTop: '0', LightLevel: '0', LightColor: '#000000'},
  3024: {ItemTypeId: '3', Name: 'mountain', Size: '2', IsBlocking: '1', IsMoveable: '0', IsPickupable: '0', IsAlwaysUnder: '0', IsAlwaysTop: '0', LightLevel: '0', LightColor: '#000000'},
  3025: {ItemTypeId: '3', Name: 'mountain', Size: '2', IsBlocking: '1', IsMoveable: '0', IsPickupable: '0', IsAlwaysUnder: '0', IsAlwaysTop: '0', LightLevel: '0', LightColor: '#000000'},
  3026: {ItemTypeId: '3', Name: 'mountain', Size: '2', IsBlocking: '1', IsMoveable: '0', IsPickupable: '0', IsAlwaysUnder: '0', IsAlwaysTop: '0', LightLevel: '0', LightColor: '#000000'},
  3027: {ItemTypeId: '3', Name: 'mountain', Size: '2', IsBlocking: '1', IsMoveable: '0', IsPickupable: '0', IsAlwaysUnder: '0', IsAlwaysTop: '0', LightLevel: '0', LightColor: '#000000'},
  3028: {ItemTypeId: '3', Name: 'mountain', Size: '2', IsBlocking: '1', IsMoveable: '0', IsPickupable: '0', IsAlwaysUnder: '0', IsAlwaysTop: '0', LightLevel: '0', LightColor: '#000000'},
  3029: {ItemTypeId: '3', Name: 'mountain', Size: '2', IsBlocking: '1', IsMoveable: '0', IsPickupable: '0', IsAlwaysUnder: '0', IsAlwaysTop: '0', LightLevel: '0', LightColor: '#000000'},
  3030: {ItemTypeId: '3', Name: 'mountain', Size: '2', IsBlocking: '1', IsMoveable: '0', IsPickupable: '0', IsAlwaysUnder: '0', IsAlwaysTop: '0', LightLevel: '0', LightColor: '#000000'},
  3031: {ItemTypeId: '3', Name: 'mountain', Size: '2', IsBlocking: '1', IsMoveable: '0', IsPickupable: '0', IsAlwaysUnder: '0', IsAlwaysTop: '0', LightLevel: '0', LightColor: '#000000'},
  3032: {ItemTypeId: '3', Name: 'mountain', Size: '2', IsBlocking: '1', IsMoveable: '0', IsPickupable: '0', IsAlwaysUnder: '0', IsAlwaysTop: '0', LightLevel: '0', LightColor: '#000000'},
  3033: {ItemTypeId: '3', Name: 'stone wall', Size: '2', IsBlocking: '1', IsMoveable: '0', IsPickupable: '0', IsAlwaysUnder: '0', IsAlwaysTop: '0', LightLevel: '0', LightColor: '#000000'},
  3034: {ItemTypeId: '3', Name: 'stone wall', Size: '2', IsBlocking: '1', IsMoveable: '0', IsPickupable: '0', IsAlwaysUnder: '0', IsAlwaysTop: '0', LightLevel: '0', LightColor: '#000000'},
  3035: {ItemTypeId: '3', Name: 'stone wall', Size: '2', IsBlocking: '1', IsMoveable: '0', IsPickupable: '0', IsAlwaysUnder: '0', IsAlwaysTop: '0', LightLevel: '0', LightColor: '#000000'},
  3036: {ItemTypeId: '3', Name: 'stone wall', Size: '2', IsBlocking: '1', IsMoveable: '0', IsPickupable: '0', IsAlwaysUnder: '0', IsAlwaysTop: '0', LightLevel: '0', LightColor: '#000000'},
  3037: {ItemTypeId: '3', Name: 'low stone wall', Size: '2', IsBlocking: '1', IsMoveable: '0', IsPickupable: '0', IsAlwaysUnder: '0', IsAlwaysTop: '0', LightLevel: '0', LightColor: '#000000'},
  3038: {ItemTypeId: '3', Name: 'low stone wall', Size: '2', IsBlocking: '1', IsMoveable: '0', IsPickupable: '0', IsAlwaysUnder: '0', IsAlwaysTop: '0', LightLevel: '0', LightColor: '#000000'},
  3039: {ItemTypeId: '3', Name: 'low stone wall', Size: '2', IsBlocking: '1', IsMoveable: '0', IsPickupable: '0', IsAlwaysUnder: '0', IsAlwaysTop: '0', LightLevel: '0', LightColor: '#000000'},
  3040: {ItemTypeId: '3', Name: 'low stone wall', Size: '2', IsBlocking: '1', IsMoveable: '0', IsPickupable: '0', IsAlwaysUnder: '0', IsAlwaysTop: '0', LightLevel: '0', LightColor: '#000000'},
  3041: {ItemTypeId: '3', Name: 'fence', Size: '2', IsBlocking: '1', IsMoveable: '0', IsPickupable: '0', IsAlwaysUnder: '0', IsAlwaysTop: '0', LightLevel: '0', LightColor: '#000000'},
  3042: {ItemTypeId: '3', Name: 'fence', Size: '2', IsBlocking: '1', IsMoveable: '0', IsPickupable: '0', IsAlwaysUnder: '0', IsAlwaysTop: '0', LightLevel: '0', LightColor: '#000000'},
  3043: {ItemTypeId: '3', Name: 'fence', Size: '2', IsBlocking: '1', IsMoveable: '0', IsPickupable: '0', IsAlwaysUnder: '0', IsAlwaysTop: '0', LightLevel: '0', LightColor: '#000000'},
  3044: {ItemTypeId: '3', Name: 'fence', Size: '2', IsBlocking: '1', IsMoveable: '0', IsPickupable: '0', IsAlwaysUnder: '0', IsAlwaysTop: '0', LightLevel: '0', LightColor: '#000000'},
  4000: {ItemTypeId: '4', Name: 'coal basin', Size: '1', IsBlocking: '1', IsMoveable: '0', IsPickupable: '0', IsAlwaysUnder: '0', IsAlwaysTop: '0', LightLevel: '0', LightColor: '#000000'},
  4001: {ItemTypeId: '4', Name: 'tree', Size: '2', IsBlocking: '1', IsMoveable: '0', IsPickupable: '0', IsAlwaysUnder: '0', IsAlwaysTop: '0', LightLevel: '0', LightColor: '#000000'},
  4002: {ItemTypeId: '4', Name: 'stone pillar', Size: '2', IsBlocking: '1', IsMoveable: '0', IsPickupable: '0', IsAlwaysUnder: '0', IsAlwaysTop: '0', LightLevel: '0', LightColor: '#000000'},
  4003: {ItemTypeId: '4', Name: 'table', Size: '2', IsBlocking: '1', IsMoveable: '0', IsPickupable: '0', IsAlwaysUnder: '0', IsAlwaysTop: '0', LightLevel: '0', LightColor: '#000000'},
  4004: {ItemTypeId: '4', Name: 'table', Size: '2', IsBlocking: '1', IsMoveable: '0', IsPickupable: '0', IsAlwaysUnder: '0', IsAlwaysTop: '0', LightLevel: '0', LightColor: '#000000'},
  4005: {ItemTypeId: '4', Name: 'table', Size: '2', IsBlocking: '1', IsMoveable: '0', IsPickupable: '0', IsAlwaysUnder: '0', IsAlwaysTop: '0', LightLevel: '0', LightColor: '#000000'},
  4006: {ItemTypeId: '4', Name: 'countertop', Size: '2', IsBlocking: '1', IsMoveable: '0', IsPickupable: '0', IsAlwaysUnder: '0', IsAlwaysTop: '0', LightLevel: '0', LightColor: '#000000'},
  4007: {ItemTypeId: '4', Name: 'countertop', Size: '2', IsBlocking: '1', IsMoveable: '0', IsPickupable: '0', IsAlwaysUnder: '0', IsAlwaysTop: '0', LightLevel: '0', LightColor: '#000000'},
  4008: {ItemTypeId: '4', Name: 'countertop', Size: '2', IsBlocking: '1', IsMoveable: '0', IsPickupable: '0', IsAlwaysUnder: '0', IsAlwaysTop: '0', LightLevel: '0', LightColor: '#000000'},
  4009: {ItemTypeId: '4', Name: 'teleport', Size: '1', IsBlocking: '0', IsMoveable: '0', IsPickupable: '0', IsAlwaysUnder: '1', IsAlwaysTop: '0', LightLevel: '0', LightColor: '#000000'},
  4010: {ItemTypeId: '4', Name: 'tree', Size: '2', IsBlocking: '1', IsMoveable: '0', IsPickupable: '0', IsAlwaysUnder: '0', IsAlwaysTop: '0', LightLevel: '0', LightColor: '#000000'},
  4011: {ItemTypeId: '4', Name: 'countertop', Size: '2', IsBlocking: '1', IsMoveable: '0', IsPickupable: '0', IsAlwaysUnder: '0', IsAlwaysTop: '0', LightLevel: '0', LightColor: '#000000'},
  4012: {ItemTypeId: '4', Name: 'countertop', Size: '2', IsBlocking: '1', IsMoveable: '0', IsPickupable: '0', IsAlwaysUnder: '0', IsAlwaysTop: '0', LightLevel: '0', LightColor: '#000000'},
  4013: {ItemTypeId: '4', Name: 'countertop', Size: '2', IsBlocking: '1', IsMoveable: '0', IsPickupable: '0', IsAlwaysUnder: '0', IsAlwaysTop: '0', LightLevel: '0', LightColor: '#000000'},
  4014: {ItemTypeId: '4', Name: 'countertop', Size: '2', IsBlocking: '1', IsMoveable: '0', IsPickupable: '0', IsAlwaysUnder: '0', IsAlwaysTop: '0', LightLevel: '0', LightColor: '#000000'},
  4015: {ItemTypeId: '4', Name: 'countertop', Size: '2', IsBlocking: '1', IsMoveable: '0', IsPickupable: '0', IsAlwaysUnder: '0', IsAlwaysTop: '0', LightLevel: '0', LightColor: '#000000'},
  4016: {ItemTypeId: '4', Name: 'countertop', Size: '2', IsBlocking: '1', IsMoveable: '0', IsPickupable: '0', IsAlwaysUnder: '0', IsAlwaysTop: '0', LightLevel: '0', LightColor: '#000000'},
  4017: {ItemTypeId: '4', Name: 'countertop', Size: '2', IsBlocking: '1', IsMoveable: '0', IsPickupable: '0', IsAlwaysUnder: '0', IsAlwaysTop: '0', LightLevel: '0', LightColor: '#000000'},
  4018: {ItemTypeId: '4', Name: 'countertop', Size: '2', IsBlocking: '1', IsMoveable: '0', IsPickupable: '0', IsAlwaysUnder: '0', IsAlwaysTop: '0', LightLevel: '0', LightColor: '#000000'},
  4019: {ItemTypeId: '4', Name: 'countertop', Size: '2', IsBlocking: '1', IsMoveable: '0', IsPickupable: '0', IsAlwaysUnder: '0', IsAlwaysTop: '0', LightLevel: '0', LightColor: '#000000'},
  4020: {ItemTypeId: '4', Name: 'countertop', Size: '2', IsBlocking: '1', IsMoveable: '0', IsPickupable: '0', IsAlwaysUnder: '0', IsAlwaysTop: '0', LightLevel: '0', LightColor: '#000000'},
  4021: {ItemTypeId: '4', Name: 'countertop', Size: '2', IsBlocking: '1', IsMoveable: '0', IsPickupable: '0', IsAlwaysUnder: '0', IsAlwaysTop: '0', LightLevel: '0', LightColor: '#000000'},
  4022: {ItemTypeId: '4', Name: 'countertop', Size: '2', IsBlocking: '1', IsMoveable: '0', IsPickupable: '0', IsAlwaysUnder: '0', IsAlwaysTop: '0', LightLevel: '0', LightColor: '#000000'},
  4023: {ItemTypeId: '4', Name: 'countertop', Size: '2', IsBlocking: '1', IsMoveable: '0', IsPickupable: '0', IsAlwaysUnder: '0', IsAlwaysTop: '0', LightLevel: '0', LightColor: '#000000'},
  4024: {ItemTypeId: '4', Name: 'countertop', Size: '2', IsBlocking: '1', IsMoveable: '0', IsPickupable: '0', IsAlwaysUnder: '0', IsAlwaysTop: '0', LightLevel: '0', LightColor: '#000000'},
  5000: {ItemTypeId: '5', Name: 'supporting beam', Size: '2', IsBlocking: '0', IsMoveable: '0', IsPickupable: '0', IsAlwaysUnder: '0', IsAlwaysTop: '1', LightLevel: '0', LightColor: '#000000'},
  5001: {ItemTypeId: '5', Name: 'supporting beam', Size: '2', IsBlocking: '0', IsMoveable: '0', IsPickupable: '0', IsAlwaysUnder: '0', IsAlwaysTop: '1', LightLevel: '0', LightColor: '#000000'},
  5002: {ItemTypeId: '5', Name: 'supporting beam', Size: '2', IsBlocking: '0', IsMoveable: '0', IsPickupable: '0', IsAlwaysUnder: '0', IsAlwaysTop: '1', LightLevel: '0', LightColor: '#000000'},
  5003: {ItemTypeId: '5', Name: 'supporting beam', Size: '2', IsBlocking: '0', IsMoveable: '0', IsPickupable: '0', IsAlwaysUnder: '0', IsAlwaysTop: '1', LightLevel: '0', LightColor: '#000000'},
  5004: {ItemTypeId: '5', Name: 'supporting beam', Size: '2', IsBlocking: '0', IsMoveable: '0', IsPickupable: '0', IsAlwaysUnder: '0', IsAlwaysTop: '1', LightLevel: '0', LightColor: '#000000'},
  5005: {ItemTypeId: '5', Name: 'supporting beam', Size: '2', IsBlocking: '0', IsMoveable: '0', IsPickupable: '0', IsAlwaysUnder: '0', IsAlwaysTop: '1', LightLevel: '0', LightColor: '#000000'},
}; 